#!/bin/bash
grep -r -s '^#include ' web.sh | while read -r result ; do
fileToImport=$(awk '{print $2}' <<< "$result")
    cat $fileToImport >> tmp
done
cat web.sh >> tmp
cp tmp web
rm tmp
chmod 555 web
mv web /usr/local/bin
