#!/bin/bash
cd web-quick-starter
source build
cd ..
rm -rf web-quick-starter
npm install bower -g
npm install wiredep -g

echo "------------------------------------------------------------------------------"
echo "Success! Web quick starter is installed. Type 'web help' to get started"
echo "------------------------------------------------------------------------------"
